[build.environment]
DART_SASS_VERSION = "1.98.0"
GO_VERSION = "1.26.1"
HUGO_VERSION = "0.158.0"
NODE_VERSION = "24.14.0"
TZ = "Europe/Oslo"

[build]
publish = "public"
command = """\
  git config core.quotepath false && \
  hugo build --gc --minify --baseURL "${URL}"
  """
